name: Android Build (Stable)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Memory and daemon settings
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx3g -XX:MaxMetaspaceSize=1g"
  # Fallback keys (override with secrets in production)
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD || 'android' }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD || 'android' }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS || 'mykey' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant gradlew permissions
        run: chmod +x gradlew

      - name: Generate temporary keystore
        if: env.KEYSTORE_FILE_BASE64 == ''
        run: |
          keytool -genkey -noprompt \
            -keystore keystore.jks \
            -alias $KEY_ALIAS \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            -dname "CN=CI, OU=Temp, O=Github, C=US"

      - name: Clean workspace
        run: ./gradlew clean --no-daemon

      - name: Build with stacktrace
        run: |
          ./gradlew assembleDebug \
            --no-daemon \
            --stacktrace \
            --info \
            -Pandroid.injected.signing.store.file=keystore.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: |
            app/build/outputs/**/*.apk
          retention-days: 3
