name: Android Build & Sign (Modern)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m"
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD || 'android' }}  # Fallback for testing
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD || 'android' }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS || 'mykey' }}

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate temporary keystore (if no secret)
        if: env.KEYSTORE_FILE_BASE64 == ''
        run: |
          keytool -genkey -noprompt \
            -keystore keystore.jks \
            -alias $KEY_ALIAS \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            -dname "CN=Temp, OU=Dev, O=Test, L=Cloud, C=CI"

      - name: Use existing keystore (if secret exists)
        if: env.KEYSTORE_FILE_BASE64 != ''
        run: |
          echo "$KEYSTORE_FILE_BASE64" | base64 -d > keystore.jks

      - name: Build and sign APK
        run: |
          ./gradlew clean assembleRelease \
            --no-daemon \
            --stacktrace \
            -Pandroid.injected.signing.store.file=keystore.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: Upload artifacts
        uses: actions/upload-artifact@v4  # Critical fix!
        with:
          name: android-builds
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
          retention-days: 7  # Auto-delete after 1 week

      - name: Upload to GitHub Releases (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2  # Updated to v2
        with:
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
