name: Build & Sign APK

on: [push, pull_request]

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Generate signing key (if none exists)
        run: |
          keytool -genkeypair \
            -v -keystore debug.keystore \
            -alias AndroidDebugKey \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass android -keypass android \
            -dname "CN=, OU=, O=, L=, S=, C="

      - name: Build and sign debug APK
        run: ./gradlew assembleDebug

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
