name: Android Auto-Key Build & Sign

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m"
  KEYSTORE_PASSWORD: "android"
  KEY_PASSWORD: "android"
  KEY_ALIAS: "mykey"

jobs:
  build-and-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate new signing key
        run: |
          keytool -genkey -noprompt \
            -keystore keystore.jks \
            -alias $KEY_ALIAS \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass $KEYSTORE_PASSWORD \
            -keypass $KEY_PASSWORD \
            -dname "CN=Android, OU=Mobile, O=Company, L=City, S=State, C=US"

      - name: Build and sign Release APK
        run: |
          ./gradlew clean assembleRelease \
            --no-daemon \
            --stacktrace \
            -Pandroid.injected.signing.store.file=keystore.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: Build and sign Release AAB
        run: |
          ./gradlew bundleRelease \
            --no-daemon \
            --stacktrace \
            -Pandroid.injected.signing.store.file=keystore.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: auto-signed-builds
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
            keystore.jks
